import type { Metadata } from "next";
import localFont from 'next/font/local'
import "./globals.css";
import SessionWrapper from "@/components/wrappers/SessionWrapper";
import QueryProviders from "@/components/wrappers/QueryProviders";
import { ThemeProvider } from "@/components/wrappers/ThemeProvider";

const jakarta = localFont({ src: "../public/fonts/PlusJakartaSans.ttf" });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={jakarta.className + " text-white bg-zinc-900 tracking-[-0.04px] flex flex-col h-svh select-none"}>
                <SessionWrapper>
                    <ThemeProvider
                        attribute="class"
                        defaultTheme="dark"
                        enableSystem={true}
                        disableTransitionOnChange
                    >
                        <QueryProviders>

                            {/* <Navigation /> */}
                            {children}
                        </QueryProviders>
                    </ThemeProvider>
                </SessionWrapper>
            </body>
        </html>
    );
}
